export interface CountryPrice {
  currency: string;
  price: number;
}

// Private AI Weekly pricing
export const COUNTRY_PRICING: Record<string, CountryPrice> = {
  "Afghanistan": { currency: "USD", price: 1.99 },
  "Albania": { currency: "USD", price: 1.99 },
  "Algeria": { currency: "USD", price: 1.99 },
  "Angola": { currency: "USD", price: 1.99 },
  "Anguilla": { currency: "USD", price: 1.99 },
  "Antigua and Barbuda": { currency: "USD", price: 1.99 },
  "Argentina": { currency: "USD", price: 1.99 },
  "Armenia": { currency: "USD", price: 1.99 },
  "Australia": { currency: "AUD", price: 2.99 },
  "Austria": { currency: "EUR", price: 1.99 },
  "Azerbaijan": { currency: "USD", price: 1.99 },
  "Bahamas": { currency: "USD", price: 1.99 },
  "Bahrain": { currency: "USD", price: 1.99 },
  "Barbados": { currency: "USD", price: 1.99 },
  "Belarus": { currency: "USD", price: 1.99 },
  "Belgium": { currency: "EUR", price: 1.99 },
  "Belize": { currency: "USD", price: 1.99 },
  "Benin": { currency: "USD", price: 1.99 },
  "Bermuda": { currency: "USD", price: 1.99 },
  "Bhutan": { currency: "USD", price: 1.99 },
  "Bolivia": { currency: "USD", price: 1.99 },
  "Bosnia and Herzegovina": { currency: "EUR", price: 1.99 },
  "Botswana": { currency: "USD", price: 1.99 },
  "Brazil": { currency: "BRL", price: 12.9 },
  "British Virgin Islands": { currency: "USD", price: 1.99 },
  "Brunei": { currency: "USD", price: 1.99 },
  "Bulgaria": { currency: "EUR", price: 1.99 },
  "Burkina Faso": { currency: "USD", price: 1.99 },
  "Cambodia": { currency: "USD", price: 1.99 },
  "Cameroon": { currency: "USD", price: 1.99 },
  "Canada": { currency: "CAD", price: 2.99 },
  "Cape Verde": { currency: "USD", price: 1.99 },
  "Cayman Islands": { currency: "USD", price: 1.99 },
  "Chad": { currency: "USD", price: 1.99 },
  "Chile": { currency: "CLP", price: 1990 },
  "China": { currency: "CNY", price: 15.0 },
  "Colombia": { currency: "COP", price: 9900.0 },
  "Congo, Democratic Republic of the": { currency: "USD", price: 1.99 },
  "Congo, Republic of the": { currency: "USD", price: 1.99 },
  "Costa Rica": { currency: "USD", price: 1.99 },
  "Côte d'Ivoire": { currency: "USD", price: 1.99 },
  "Croatia": { currency: "EUR", price: 1.99 },
  "Cyprus": { currency: "EUR", price: 1.99 },
  "Czech Republic": { currency: "CZK", price: 49.0 },
  "Denmark": { currency: "DKK", price: 19.0 },
  "Dominica": { currency: "USD", price: 1.99 },
  "Dominican Republic": { currency: "USD", price: 1.99 },
  "Ecuador": { currency: "USD", price: 1.99 },
  "Egypt": { currency: "EGP", price: 99.99 },
  "El Salvador": { currency: "USD", price: 1.99 },
  "Estonia": { currency: "EUR", price: 1.99 },
  "Eswatini": { currency: "USD", price: 1.99 },
  "Fiji": { currency: "USD", price: 1.99 },
  "Finland": { currency: "EUR", price: 1.99 },
  "France": { currency: "EUR", price: 1.99 },
  "Gabon": { currency: "USD", price: 1.99 },
  "Gambia": { currency: "USD", price: 1.99 },
  "Georgia": { currency: "USD", price: 1.99 },
  "Germany": { currency: "EUR", price: 1.99 },
  "Ghana": { currency: "USD", price: 1.99 },
  "Greece": { currency: "EUR", price: 1.99 },
  "Grenada": { currency: "USD", price: 1.99 },
  "Guatemala": { currency: "USD", price: 1.99 },
  "Guinea-Bissau": { currency: "USD", price: 1.99 },
  "Guyana": { currency: "USD", price: 1.99 },
  "Honduras": { currency: "USD", price: 1.99 },
  "Hong Kong": { currency: "HKD", price: 18.0 },
  "Hungary": { currency: "HUF", price: 999 },
  "Iceland": { currency: "USD", price: 1.99 },
  "India": { currency: "INR", price: 199.0 },
  "Indonesia": { currency: "IDR", price: 29000 },
  "Iraq": { currency: "USD", price: 1.99 },
  "Ireland": { currency: "EUR", price: 1.99 },
  "Israel": { currency: "ILS", price: 7.9 },
  "Italy": { currency: "EUR", price: 1.99 },
  "Jamaica": { currency: "USD", price: 1.99 },
  "Japan": { currency: "JPY", price: 300 },
  "Jordan": { currency: "USD", price: 1.99 },
  "Kazakhstan": { currency: "KZT", price: 999.0 },
  "Kenya": { currency: "USD", price: 1.99 },
  "Korea, Republic of": { currency: "KRW", price: 3300 },
  "Kosovo": { currency: "EUR", price: 1.99 },
  "Kuwait": { currency: "USD", price: 1.99 },
  "Kyrgyzstan": { currency: "USD", price: 1.99 },
  "Laos": { currency: "USD", price: 1.99 },
  "Latvia": { currency: "EUR", price: 1.99 },
  "Lebanon": { currency: "USD", price: 1.99 },
  "Liberia": { currency: "USD", price: 1.99 },
  "Libya": { currency: "USD", price: 1.99 },
  "Lithuania": { currency: "EUR", price: 1.99 },
  "Luxembourg": { currency: "EUR", price: 1.99 },
  "Macau": { currency: "USD", price: 1.99 },
  "Madagascar": { currency: "USD", price: 1.99 },
  "Malawi": { currency: "USD", price: 1.99 },
  "Malaysia": { currency: "MYR", price: 9.9 },
  "Maldives": { currency: "USD", price: 1.99 },
  "Mali": { currency: "USD", price: 1.99 },
  "Malta": { currency: "EUR", price: 1.99 },
  "Mauritania": { currency: "USD", price: 1.99 },
  "Mauritius": { currency: "USD", price: 1.99 },
  "Mexico": { currency: "MXN", price: 39.0 },
  "Micronesia": { currency: "USD", price: 1.99 },
  "Moldova": { currency: "USD", price: 1.99 },
  "Mongolia": { currency: "USD", price: 1.99 },
  "Montenegro": { currency: "EUR", price: 1.99 },
  "Montserrat": { currency: "USD", price: 1.99 },
  "Morocco": { currency: "USD", price: 1.99 },
  "Mozambique": { currency: "USD", price: 1.99 },
  "Myanmar": { currency: "USD", price: 1.99 },
  "Namibia": { currency: "USD", price: 1.99 },
  "Nauru": { currency: "USD", price: 1.99 },
  "Nepal": { currency: "USD", price: 1.99 },
  "Netherlands": { currency: "EUR", price: 1.99 },
  "New Zealand": { currency: "NZD", price: 3.99 },
  "Nicaragua": { currency: "USD", price: 1.99 },
  "Niger": { currency: "USD", price: 1.99 },
  "Nigeria": { currency: "NGN", price: 3200.0 },
  "North Macedonia": { currency: "USD", price: 1.99 },
  "Norway": { currency: "NOK", price: 29.0 },
  "Oman": { currency: "USD", price: 1.99 },
  "Pakistan": { currency: "PKR", price: 500.0 },
  "Palau": { currency: "USD", price: 1.99 },
  "Panama": { currency: "USD", price: 1.99 },
  "Papua New Guinea": { currency: "USD", price: 1.99 },
  "Paraguay": { currency: "USD", price: 1.99 },
  "Peru": { currency: "PEN", price: 9.9 },
  "Philippines": { currency: "PHP", price: 129.0 },
  "Poland": { currency: "PLN", price: 9.99 },
  "Portugal": { currency: "EUR", price: 1.99 },
  "Qatar": { currency: "QAR", price: 7.99 },
  "Romania": { currency: "RON", price: 9.99 },
  "Russia": { currency: "RUB", price: 199.0 },
  "Rwanda": { currency: "USD", price: 1.99 },
  "São Tomé and Príncipe": { currency: "USD", price: 1.99 },
  "Saudi Arabia": { currency: "SAR", price: 9.99 },
  "Senegal": { currency: "USD", price: 1.99 },
  "Serbia": { currency: "EUR", price: 1.99 },
  "Seychelles": { currency: "USD", price: 1.99 },
  "Sierra Leone": { currency: "USD", price: 1.99 },
  "Singapore": { currency: "SGD", price: 2.98 },
  "Slovakia": { currency: "EUR", price: 1.99 },
  "Slovenia": { currency: "EUR", price: 1.99 },
  "Solomon Islands": { currency: "USD", price: 1.99 },
  "South Africa": { currency: "ZAR", price: 39.99 },
  "Spain": { currency: "EUR", price: 1.99 },
  "Sri Lanka": { currency: "USD", price: 1.99 },
  "St. Kitts and Nevis": { currency: "USD", price: 1.99 },
  "St. Lucia": { currency: "USD", price: 1.99 },
  "St. Vincent and the Grenadines": { currency: "USD", price: 1.99 },
  "Suriname": { currency: "USD", price: 1.99 },
  "Sweden": { currency: "SEK", price: 29.0 },
  "Switzerland": { currency: "CHF", price: 2.0 },
  "Taiwan": { currency: "TWD", price: 60 },
  "Tajikistan": { currency: "USD", price: 1.99 },
  "Tanzania": { currency: "TZS", price: 5900.0 },
  "Thailand": { currency: "THB", price: 79.0 },
  "Tonga": { currency: "USD", price: 1.99 },
  "Trinidad and Tobago": { currency: "USD", price: 1.99 },
  "Tunisia": { currency: "USD", price: 1.99 },
  "Türkiye": { currency: "TRY", price: 99.99 },
  "Turkmenistan": { currency: "USD", price: 1.99 },
  "Turks and Caicos Islands": { currency: "USD", price: 1.99 },
  "Uganda": { currency: "USD", price: 1.99 },
  "Ukraine": { currency: "USD", price: 1.99 },
  "United Arab Emirates": { currency: "AED", price: 7.99 },
  "United Kingdom": { currency: "GBP", price: 1.99 },
  "United States": { currency: "USD", price: 1.99 },
  "Uruguay": { currency: "USD", price: 1.99 },
  "Uzbekistan": { currency: "USD", price: 1.99 },
  "Vanuatu": { currency: "USD", price: 1.99 },
  "Venezuela": { currency: "USD", price: 1.99 },
  "Vietnam": { currency: "VND", price: 59000 },
  "Yemen": { currency: "USD", price: 1.99 },
  "Zambia": { currency: "USD", price: 1.99 },
  "Zimbabwe": { currency: "USD", price: 1.99 },
};

// Cloud AI Weekly pricing
export const CLOUD_AI_WEEKLY_PRICING: Record<string, CountryPrice> = {
  "Afghanistan": { currency: "USD", price: 6.99 },
  "Albania": { currency: "USD", price: 7.99 },
  "Algeria": { currency: "USD", price: 6.99 },
  "Angola": { currency: "USD", price: 6.99 },
  "Anguilla": { currency: "USD", price: 6.99 },
  "Antigua and Barbuda": { currency: "USD", price: 6.99 },
  "Argentina": { currency: "USD", price: 6.99 },
  "Armenia": { currency: "USD", price: 7.99 },
  "Australia": { currency: "AUD", price: 9.99 },
  "Austria": { currency: "EUR", price: 7.99 },
  "Azerbaijan": { currency: "USD", price: 7.99 },
  "Bahamas": { currency: "USD", price: 7.99 },
  "Bahrain": { currency: "USD", price: 7.99 },
  "Barbados": { currency: "USD", price: 7.99 },
  "Belarus": { currency: "USD", price: 7.99 },
  "Belgium": { currency: "EUR", price: 7.99 },
  "Belize": { currency: "USD", price: 6.99 },
  "Benin": { currency: "USD", price: 7.99 },
  "Bermuda": { currency: "USD", price: 6.99 },
  "Bhutan": { currency: "USD", price: 6.99 },
  "Bolivia": { currency: "USD", price: 6.99 },
  "Bosnia and Herzegovina": { currency: "EUR", price: 7.99 },
  "Botswana": { currency: "USD", price: 6.99 },
  "Brazil": { currency: "BRL", price: 49.9 },
  "British Virgin Islands": { currency: "USD", price: 6.99 },
  "Brunei": { currency: "USD", price: 6.99 },
  "Bulgaria": { currency: "EUR", price: 7.99 },
  "Burkina Faso": { currency: "USD", price: 6.99 },
  "Cambodia": { currency: "USD", price: 7.99 },
  "Cameroon": { currency: "USD", price: 7.99 },
  "Canada": { currency: "CAD", price: 9.99 },
  "Cape Verde": { currency: "USD", price: 6.99 },
  "Cayman Islands": { currency: "USD", price: 6.99 },
  "Chad": { currency: "USD", price: 6.99 },
  "Chile": { currency: "CLP", price: 7990 },
  "China mainland": { currency: "CNY", price: 48.0 },
  "Colombia": { currency: "COP", price: 29900.0 },
  "Congo, Democratic Republic of the": { currency: "USD", price: 6.99 },
  "Congo, Republic of the": { currency: "USD", price: 6.99 },
  "Costa Rica": { currency: "USD", price: 6.99 },
  "Côte d'Ivoire": { currency: "USD", price: 7.99 },
  "Croatia": { currency: "EUR", price: 7.99 },
  "Cyprus": { currency: "EUR", price: 7.99 },
  "Czech Republic": { currency: "CZK", price: 199.0 },
  "Denmark": { currency: "DKK", price: 59.0 },
  "Dominica": { currency: "USD", price: 6.99 },
  "Dominican Republic": { currency: "USD", price: 6.99 },
  "Ecuador": { currency: "USD", price: 6.99 },
  "Egypt": { currency: "EGP", price: 399.99 },
  "El Salvador": { currency: "USD", price: 6.99 },
  "Estonia": { currency: "EUR", price: 7.99 },
  "Eswatini": { currency: "USD", price: 6.99 },
  "Fiji": { currency: "USD", price: 6.99 },
  "Finland": { currency: "EUR", price: 7.99 },
  "France": { currency: "EUR", price: 7.99 },
  "Gabon": { currency: "USD", price: 6.99 },
  "Gambia": { currency: "USD", price: 6.99 },
  "Georgia": { currency: "USD", price: 7.99 },
  "Germany": { currency: "EUR", price: 7.99 },
  "Ghana": { currency: "USD", price: 7.99 },
  "Greece": { currency: "EUR", price: 7.99 },
  "Grenada": { currency: "USD", price: 6.99 },
  "Guatemala": { currency: "USD", price: 6.99 },
  "Guinea-Bissau": { currency: "USD", price: 6.99 },
  "Guyana": { currency: "USD", price: 6.99 },
  "Honduras": { currency: "USD", price: 6.99 },
  "Hong Kong": { currency: "HKD", price: 58.0 },
  "Hungary": { currency: "HUF", price: 2990 },
  "Iceland": { currency: "USD", price: 7.99 },
  "India": { currency: "INR", price: 699.0 },
  "Indonesia": { currency: "IDR", price: 119000 },
  "Iraq": { currency: "USD", price: 6.99 },
  "Ireland": { currency: "EUR", price: 7.99 },
  "Israel": { currency: "ILS", price: 24.9 },
  "Italy": { currency: "EUR", price: 7.99 },
  "Jamaica": { currency: "USD", price: 6.99 },
  "Japan": { currency: "JPY", price: 1100 },
  "Jordan": { currency: "USD", price: 6.99 },
  "Kazakhstan": { currency: "KZT", price: 3990.0 },
  "Kenya": { currency: "USD", price: 7.99 },
  "Korea, Republic of": { currency: "KRW", price: 9900 },
  "Kosovo": { currency: "EUR", price: 7.99 },
  "Kuwait": { currency: "USD", price: 6.99 },
  "Kyrgyzstan": { currency: "USD", price: 7.99 },
  "Laos": { currency: "USD", price: 7.99 },
  "Latvia": { currency: "EUR", price: 7.99 },
  "Lebanon": { currency: "USD", price: 6.99 },
  "Liberia": { currency: "USD", price: 6.99 },
  "Libya": { currency: "USD", price: 6.99 },
  "Lithuania": { currency: "EUR", price: 7.99 },
  "Luxembourg": { currency: "EUR", price: 7.99 },
  "Macau": { currency: "USD", price: 6.99 },
  "Madagascar": { currency: "USD", price: 6.99 },
  "Malawi": { currency: "USD", price: 6.99 },
  "Malaysia": { currency: "MYR", price: 29.9 },
  "Maldives": { currency: "USD", price: 6.99 },
  "Mali": { currency: "USD", price: 6.99 },
  "Malta": { currency: "EUR", price: 7.99 },
  "Mauritania": { currency: "USD", price: 6.99 },
  "Mauritius": { currency: "USD", price: 6.99 },
  "Mexico": { currency: "MXN", price: 149.0 },
  "Micronesia": { currency: "USD", price: 6.99 },
  "Moldova": { currency: "USD", price: 7.99 },
  "Mongolia": { currency: "USD", price: 6.99 },
  "Montenegro": { currency: "EUR", price: 6.99 },
  "Montserrat": { currency: "USD", price: 6.99 },
  "Morocco": { currency: "USD", price: 6.99 },
  "Mozambique": { currency: "USD", price: 6.99 },
  "Myanmar": { currency: "USD", price: 6.99 },
  "Namibia": { currency: "USD", price: 6.99 },
  "Nauru": { currency: "USD", price: 6.99 },
  "Nepal": { currency: "USD", price: 7.99 },
  "Netherlands": { currency: "EUR", price: 7.99 },
  "New Zealand": { currency: "NZD", price: 12.99 },
  "Nicaragua": { currency: "USD", price: 6.99 },
  "Niger": { currency: "USD", price: 6.99 },
  "Nigeria": { currency: "NGN", price: 9900.0 },
  "North Macedonia": { currency: "USD", price: 6.99 },
  "Norway": { currency: "NOK", price: 89.0 },
  "Oman": { currency: "USD", price: 6.99 },
  "Pakistan": { currency: "PKR", price: 1900.0 },
  "Palau": { currency: "USD", price: 6.99 },
  "Panama": { currency: "USD", price: 6.99 },
  "Papua New Guinea": { currency: "USD", price: 6.99 },
  "Paraguay": { currency: "USD", price: 6.99 },
  "Peru": { currency: "PEN", price: 29.9 },
  "Philippines": { currency: "PHP", price: 449.0 },
  "Poland": { currency: "PLN", price: 29.99 },
  "Portugal": { currency: "EUR", price: 7.99 },
  "Qatar": { currency: "QAR", price: 24.99 },
  "Romania": { currency: "RON", price: 39.99 },
  "Russia": { currency: "RUB", price: 599.0 },
  "Rwanda": { currency: "USD", price: 6.99 },
  "São Tomé and Príncipe": { currency: "USD", price: 6.99 },
  "Saudi Arabia": { currency: "SAR", price: 29.99 },
  "Senegal": { currency: "USD", price: 7.99 },
  "Serbia": { currency: "EUR", price: 7.99 },
  "Seychelles": { currency: "USD", price: 6.99 },
  "Sierra Leone": { currency: "USD", price: 6.99 },
  "Singapore": { currency: "SGD", price: 9.98 },
  "Slovakia": { currency: "EUR", price: 7.99 },
  "Slovenia": { currency: "EUR", price: 7.99 },
  "Solomon Islands": { currency: "USD", price: 6.99 },
  "South Africa": { currency: "ZAR", price: 149.99 },
  "Spain": { currency: "EUR", price: 7.99 },
  "Sri Lanka": { currency: "USD", price: 6.99 },
  "St. Kitts and Nevis": { currency: "USD", price: 6.99 },
  "St. Lucia": { currency: "USD", price: 6.99 },
  "St. Vincent and the Grenadines": { currency: "USD", price: 6.99 },
  "Suriname": { currency: "USD", price: 7.99 },
  "Sweden": { currency: "SEK", price: 99.0 },
  "Switzerland": { currency: "CHF", price: 6.0 },
  "Taiwan": { currency: "TWD", price: 220 },
  "Tajikistan": { currency: "USD", price: 7.99 },
  "Tanzania": { currency: "TZS", price: 19900.0 },
  "Thailand": { currency: "THB", price: 249.0 },
  "Tonga": { currency: "USD", price: 6.99 },
  "Trinidad and Tobago": { currency: "USD", price: 6.99 },
  "Tunisia": { currency: "USD", price: 6.99 },
  "Türkiye": { currency: "TRY", price: 399.99 },
  "Turkmenistan": { currency: "USD", price: 6.99 },
  "Turks and Caicos Islands": { currency: "USD", price: 6.99 },
  "Uganda": { currency: "USD", price: 7.99 },
  "Ukraine": { currency: "USD", price: 7.99 },
  "United Arab Emirates": { currency: "AED", price: 24.99 },
  "United Kingdom": { currency: "GBP", price: 6.99 },
  "United States": { currency: "USD", price: 6.99 },
  "Uruguay": { currency: "USD", price: 6.99 },
  "Uzbekistan": { currency: "USD", price: 7.99 },
  "Vanuatu": { currency: "USD", price: 6.99 },
  "Venezuela": { currency: "USD", price: 6.99 },
  "Vietnam": { currency: "VND", price: 199000 },
  "Yemen": { currency: "USD", price: 6.99 },
  "Zambia": { currency: "USD", price: 7.99 },
  "Zimbabwe": { currency: "USD", price: 7.99 },
};

// Private AI Yearly pricing
export const PRIVATE_AI_YEARLY_PRICING: Record<string, CountryPrice> = {
  "Afghanistan": { currency: "USD", price: 19.99 },
  "Albania": { currency: "USD", price: 22.99 },
  "Algeria": { currency: "USD", price: 19.99 },
  "Angola": { currency: "USD", price: 19.99 },
  "Anguilla": { currency: "USD", price: 19.99 },
  "Antigua and Barbuda": { currency: "USD", price: 19.99 },
  "Argentina": { currency: "USD", price: 19.99 },
  "Armenia": { currency: "USD", price: 22.99 },
  "Australia": { currency: "AUD", price: 29.99 },
  "Austria": { currency: "EUR", price: 22.99 },
  "Azerbaijan": { currency: "USD", price: 22.99 },
  "Bahamas": { currency: "USD", price: 19.99 },
  "Bahrain": { currency: "USD", price: 19.99 },
  "Barbados": { currency: "USD", price: 22.99 },
  "Belarus": { currency: "USD", price: 22.99 },
  "Belgium": { currency: "EUR", price: 22.99 },
  "Belize": { currency: "USD", price: 19.99 },
  "Benin": { currency: "USD", price: 22.99 },
  "Bermuda": { currency: "USD", price: 19.99 },
  "Bhutan": { currency: "USD", price: 19.99 },
  "Bolivia": { currency: "USD", price: 19.99 },
  "Bosnia and Herzegovina": { currency: "EUR", price: 22.99 },
  "Botswana": { currency: "USD", price: 19.99 },
  "Brazil": { currency: "BRL", price: 129.9 },
  "British Virgin Islands": { currency: "USD", price: 19.99 },
  "Brunei": { currency: "USD", price: 19.99 },
  "Bulgaria": { currency: "EUR", price: 19.99 },
  "Burkina Faso": { currency: "USD", price: 19.99 },
  "Cambodia": { currency: "USD", price: 19.99 },
  "Cameroon": { currency: "USD", price: 22.99 },
  "Canada": { currency: "CAD", price: 24.99 },
  "Cape Verde": { currency: "USD", price: 19.99 },
  "Cayman Islands": { currency: "USD", price: 19.99 },
  "Chad": { currency: "USD", price: 19.99 },
  "Chile": { currency: "CLP", price: 22990 },
  "China mainland": { currency: "CNY", price: 148.0 },
  "Colombia": { currency: "COP", price: 99900.0 },
  "Congo, Democratic Republic of the": { currency: "USD", price: 19.99 },
  "Congo, Republic of the": { currency: "USD", price: 19.99 },
  "Costa Rica": { currency: "USD", price: 19.99 },
  "Côte d'Ivoire": { currency: "USD", price: 22.99 },
  "Croatia": { currency: "EUR", price: 22.99 },
  "Cyprus": { currency: "EUR", price: 22.99 },
  "Czech Republic": { currency: "CZK", price: 499.0 },
  "Denmark": { currency: "DKK", price: 179.0 },
  "Dominica": { currency: "USD", price: 19.99 },
  "Dominican Republic": { currency: "USD", price: 19.99 },
  "Ecuador": { currency: "USD", price: 19.99 },
  "Egypt": { currency: "EGP", price: 999.99 },
  "El Salvador": { currency: "USD", price: 19.99 },
  "Estonia": { currency: "EUR", price: 22.99 },
  "Eswatini": { currency: "USD", price: 19.99 },
  "Fiji": { currency: "USD", price: 19.99 },
  "Finland": { currency: "EUR", price: 22.99 },
  "France": { currency: "EUR", price: 22.99 },
  "Gabon": { currency: "USD", price: 19.99 },
  "Gambia": { currency: "USD", price: 19.99 },
  "Georgia": { currency: "USD", price: 22.99 },
  "Germany": { currency: "EUR", price: 22.99 },
  "Ghana": { currency: "USD", price: 22.99 },
  "Greece": { currency: "EUR", price: 22.99 },
  "Grenada": { currency: "USD", price: 19.99 },
  "Guatemala": { currency: "USD", price: 19.99 },
  "Guinea-Bissau": { currency: "USD", price: 19.99 },
  "Guyana": { currency: "USD", price: 19.99 },
  "Honduras": { currency: "USD", price: 19.99 },
  "Hong Kong": { currency: "HKD", price: 148.0 },
  "Hungary": { currency: "HUF", price: 8990 },
  "Iceland": { currency: "USD", price: 22.99 },
  "India": { currency: "INR", price: 1999.0 },
  "Indonesia": { currency: "IDR", price: 349000 },
  "Iraq": { currency: "USD", price: 19.99 },
  "Ireland": { currency: "EUR", price: 22.99 },
  "Israel": { currency: "ILS", price: 69.9 },
  "Italy": { currency: "EUR", price: 22.99 },
  "Jamaica": { currency: "USD", price: 19.99 },
  "Japan": { currency: "JPY", price: 3000 },
  "Jordan": { currency: "USD", price: 19.99 },
  "Kazakhstan": { currency: "KZT", price: 11990.0 },
  "Kenya": { currency: "USD", price: 22.99 },
  "Korea, Republic of": { currency: "KRW", price: 29000 },
  "Kosovo": { currency: "EUR", price: 22.99 },
  "Kuwait": { currency: "USD", price: 19.99 },
  "Kyrgyzstan": { currency: "USD", price: 19.99 },
  "Laos": { currency: "USD", price: 19.99 },
  "Latvia": { currency: "EUR", price: 22.99 },
  "Lebanon": { currency: "USD", price: 19.99 },
  "Liberia": { currency: "USD", price: 19.99 },
  "Libya": { currency: "USD", price: 19.99 },
  "Lithuania": { currency: "EUR", price: 22.99 },
  "Luxembourg": { currency: "EUR", price: 22.99 },
  "Macau": { currency: "USD", price: 19.99 },
  "Madagascar": { currency: "USD", price: 19.99 },
  "Malawi": { currency: "USD", price: 19.99 },
  "Malaysia": { currency: "MYR", price: 99.9 },
  "Maldives": { currency: "USD", price: 19.99 },
  "Mali": { currency: "USD", price: 19.99 },
  "Malta": { currency: "EUR", price: 22.99 },
  "Mauritania": { currency: "USD", price: 19.99 },
  "Mauritius": { currency: "USD", price: 19.99 },
  "Mexico": { currency: "MXN", price: 399.0 },
  "Micronesia": { currency: "USD", price: 19.99 },
  "Moldova": { currency: "USD", price: 22.99 },
  "Mongolia": { currency: "USD", price: 19.99 },
  "Montenegro": { currency: "EUR", price: 19.99 },
  "Montserrat": { currency: "USD", price: 19.99 },
  "Morocco": { currency: "USD", price: 19.99 },
  "Mozambique": { currency: "USD", price: 19.99 },
  "Myanmar": { currency: "USD", price: 19.99 },
  "Namibia": { currency: "USD", price: 19.99 },
  "Nauru": { currency: "USD", price: 19.99 },
  "Nepal": { currency: "USD", price: 22.99 },
  "Netherlands": { currency: "EUR", price: 22.99 },
  "New Zealand": { currency: "NZD", price: 39.99 },
  "Nicaragua": { currency: "USD", price: 19.99 },
  "Niger": { currency: "USD", price: 19.99 },
  "Nigeria": { currency: "NGN", price: 19900.0 },
  "North Macedonia": { currency: "USD", price: 19.99 },
  "Norway": { currency: "NOK", price: 249.0 },
  "Oman": { currency: "USD", price: 19.99 },
  "Pakistan": { currency: "PKR", price: 4900.0 },
  "Palau": { currency: "USD", price: 19.99 },
  "Panama": { currency: "USD", price: 19.99 },
  "Papua New Guinea": { currency: "USD", price: 19.99 },
  "Paraguay": { currency: "USD", price: 19.99 },
  "Peru": { currency: "PEN", price: 89.9 },
  "Philippines": { currency: "PHP", price: 1290.0 },
  "Poland": { currency: "PLN", price: 99.99 },
  "Portugal": { currency: "EUR", price: 22.99 },
  "Qatar": { currency: "QAR", price: 69.99 },
  "Romania": { currency: "RON", price: 99.99 },
  "Russia": { currency: "RUB", price: 1790.0 },
  "Rwanda": { currency: "USD", price: 19.99 },
  "São Tomé and Príncipe": { currency: "USD", price: 19.99 },
  "Saudi Arabia": { currency: "SAR", price: 89.99 },
  "Senegal": { currency: "USD", price: 22.99 },
  "Serbia": { currency: "EUR", price: 22.99 },
  "Seychelles": { currency: "USD", price: 19.99 },
  "Sierra Leone": { currency: "USD", price: 19.99 },
  "Singapore": { currency: "SGD", price: 29.98 },
  "Slovakia": { currency: "EUR", price: 22.99 },
  "Slovenia": { currency: "EUR", price: 22.99 },
  "Solomon Islands": { currency: "USD", price: 19.99 },
  "South Africa": { currency: "ZAR", price: 399.99 },
  "Spain": { currency: "EUR", price: 22.99 },
  "Sri Lanka": { currency: "USD", price: 19.99 },
  "St. Kitts and Nevis": { currency: "USD", price: 19.99 },
  "St. Lucia": { currency: "USD", price: 19.99 },
  "St. Vincent and the Grenadines": { currency: "USD", price: 19.99 },
  "Suriname": { currency: "USD", price: 19.99 },
  "Sweden": { currency: "SEK", price: 249.0 },
  "Switzerland": { currency: "CHF", price: 18.0 },
  "Taiwan": { currency: "TWD", price: 690 },
  "Tajikistan": { currency: "USD", price: 19.99 },
  "Tanzania": { currency: "TZS", price: 59900.0 },
  "Thailand": { currency: "THB", price: 699.0 },
  "Tonga": { currency: "USD", price: 19.99 },
  "Trinidad and Tobago": { currency: "USD", price: 19.99 },
  "Tunisia": { currency: "USD", price: 19.99 },
  "Türkiye": { currency: "TRY", price: 999.99 },
  "Turkmenistan": { currency: "USD", price: 19.99 },
  "Turks and Caicos Islands": { currency: "USD", price: 19.99 },
  "Uganda": { currency: "USD", price: 22.99 },
  "Ukraine": { currency: "USD", price: 22.99 },
  "United Arab Emirates": { currency: "AED", price: 79.99 },
  "United Kingdom": { currency: "GBP", price: 19.99 },
  "United States": { currency: "USD", price: 19.99 },
  "Uruguay": { currency: "USD", price: 19.99 },
  "Uzbekistan": { currency: "USD", price: 19.99 },
  "Vanuatu": { currency: "USD", price: 19.99 },
  "Venezuela": { currency: "USD", price: 19.99 },
  "Vietnam": { currency: "VND", price: 599000 },
  "Yemen": { currency: "USD", price: 19.99 },
  "Zambia": { currency: "USD", price: 22.99 },
  "Zimbabwe": { currency: "USD", price: 22.99 },
};

// Cloud AI Yearly pricing
export const CLOUD_AI_YEARLY_PRICING: Record<string, CountryPrice> = {
  "Afghanistan": { currency: "USD", price: 69.99 },
  "Albania": { currency: "USD", price: 79.99 },
  "Algeria": { currency: "USD", price: 69.99 },
  "Angola": { currency: "USD", price: 69.99 },
  "Anguilla": { currency: "USD", price: 69.99 },
  "Antigua and Barbuda": { currency: "USD", price: 69.99 },
  "Argentina": { currency: "USD", price: 69.99 },
  "Armenia": { currency: "USD", price: 79.99 },
  "Australia": { currency: "AUD", price: 99.99 },
  "Austria": { currency: "EUR", price: 79.99 },
  "Azerbaijan": { currency: "USD", price: 79.99 },
  "Bahamas": { currency: "USD", price: 79.99 },
  "Bahrain": { currency: "USD", price: 79.99 },
  "Barbados": { currency: "USD", price: 79.99 },
  "Belarus": { currency: "USD", price: 79.99 },
  "Belgium": { currency: "EUR", price: 79.99 },
  "Belize": { currency: "USD", price: 69.99 },
  "Benin": { currency: "USD", price: 79.99 },
  "Bermuda": { currency: "USD", price: 69.99 },
  "Bhutan": { currency: "USD", price: 69.99 },
  "Bolivia": { currency: "USD", price: 69.99 },
  "Bosnia and Herzegovina": { currency: "EUR", price: 79.99 },
  "Botswana": { currency: "USD", price: 69.99 },
  "Brazil": { currency: "BRL", price: 499.9 },
  "British Virgin Islands": { currency: "USD", price: 69.99 },
  "Brunei": { currency: "USD", price: 69.99 },
  "Bulgaria": { currency: "EUR", price: 79.99 },
  "Burkina Faso": { currency: "USD", price: 69.99 },
  "Cambodia": { currency: "USD", price: 79.99 },
  "Cameroon": { currency: "USD", price: 79.99 },
  "Canada": { currency: "CAD", price: 99.99 },
  "Cape Verde": { currency: "USD", price: 69.99 },
  "Cayman Islands": { currency: "USD", price: 69.99 },
  "Chad": { currency: "USD", price: 69.99 },
  "Chile": { currency: "CLP", price: 79990 },
  "China mainland": { currency: "CNY", price: 498.0 },
  "Colombia": { currency: "COP", price: 299900.0 },
  "Congo, Democratic Republic of the": { currency: "USD", price: 69.99 },
  "Congo, Republic of the": { currency: "USD", price: 69.99 },
  "Costa Rica": { currency: "USD", price: 69.99 },
  "Côte d'Ivoire": { currency: "USD", price: 79.99 },
  "Croatia": { currency: "EUR", price: 79.99 },
  "Cyprus": { currency: "EUR", price: 79.99 },
  "Czech Republic": { currency: "CZK", price: 1990.0 },
  "Denmark": { currency: "DKK", price: 599.0 },
  "Dominica": { currency: "USD", price: 69.99 },
  "Dominican Republic": { currency: "USD", price: 69.99 },
  "Ecuador": { currency: "USD", price: 69.99 },
  "Egypt": { currency: "EGP", price: 3999.99 },
  "El Salvador": { currency: "USD", price: 69.99 },
  "Estonia": { currency: "EUR", price: 79.99 },
  "Eswatini": { currency: "USD", price: 69.99 },
  "Fiji": { currency: "USD", price: 69.99 },
  "Finland": { currency: "EUR", price: 79.99 },
  "France": { currency: "EUR", price: 79.99 },
  "Gabon": { currency: "USD", price: 69.99 },
  "Gambia": { currency: "USD", price: 69.99 },
  "Georgia": { currency: "USD", price: 79.99 },
  "Germany": { currency: "EUR", price: 79.99 },
  "Ghana": { currency: "USD", price: 79.99 },
  "Greece": { currency: "EUR", price: 79.99 },
  "Grenada": { currency: "USD", price: 69.99 },
  "Guatemala": { currency: "USD", price: 69.99 },
  "Guinea-Bissau": { currency: "USD", price: 69.99 },
  "Guyana": { currency: "USD", price: 69.99 },
  "Honduras": { currency: "USD", price: 69.99 },
  "Hong Kong": { currency: "HKD", price: 588.0 },
  "Hungary": { currency: "HUF", price: 29990 },
  "Iceland": { currency: "USD", price: 79.99 },
  "India": { currency: "INR", price: 6900.0 },
  "Indonesia": { currency: "IDR", price: 1199000 },
  "Iraq": { currency: "USD", price: 69.99 },
  "Ireland": { currency: "EUR", price: 79.99 },
  "Israel": { currency: "ILS", price: 249.9 },
  "Italy": { currency: "EUR", price: 79.99 },
  "Jamaica": { currency: "USD", price: 69.99 },
  "Japan": { currency: "JPY", price: 11000 },
  "Jordan": { currency: "USD", price: 69.99 },
  "Kazakhstan": { currency: "KZT", price: 39990.0 },
  "Kenya": { currency: "USD", price: 79.99 },
  "Korea, Republic of": { currency: "KRW", price: 99000 },
  "Kosovo": { currency: "EUR", price: 79.99 },
  "Kuwait": { currency: "USD", price: 69.99 },
  "Kyrgyzstan": { currency: "USD", price: 79.99 },
  "Laos": { currency: "USD", price: 79.99 },
  "Latvia": { currency: "EUR", price: 79.99 },
  "Lebanon": { currency: "USD", price: 69.99 },
  "Liberia": { currency: "USD", price: 69.99 },
  "Libya": { currency: "USD", price: 69.99 },
  "Lithuania": { currency: "EUR", price: 79.99 },
  "Luxembourg": { currency: "EUR", price: 79.99 },
  "Macau": { currency: "USD", price: 69.99 },
  "Madagascar": { currency: "USD", price: 69.99 },
  "Malawi": { currency: "USD", price: 69.99 },
  "Malaysia": { currency: "MYR", price: 299.9 },
  "Maldives": { currency: "USD", price: 69.99 },
  "Mali": { currency: "USD", price: 69.99 },
  "Malta": { currency: "EUR", price: 79.99 },
  "Mauritania": { currency: "USD", price: 69.99 },
  "Mauritius": { currency: "USD", price: 69.99 },
  "Mexico": { currency: "MXN", price: 1499.0 },
  "Micronesia": { currency: "USD", price: 69.99 },
  "Moldova": { currency: "USD", price: 79.99 },
  "Mongolia": { currency: "USD", price: 69.99 },
  "Montenegro": { currency: "EUR", price: 69.99 },
  "Montserrat": { currency: "USD", price: 69.99 },
  "Morocco": { currency: "USD", price: 69.99 },
  "Mozambique": { currency: "USD", price: 69.99 },
  "Myanmar": { currency: "USD", price: 69.99 },
  "Namibia": { currency: "USD", price: 69.99 },
  "Nauru": { currency: "USD", price: 69.99 },
  "Nepal": { currency: "USD", price: 79.99 },
  "Netherlands": { currency: "EUR", price: 79.99 },
  "New Zealand": { currency: "NZD", price: 129.99 },
  "Nicaragua": { currency: "USD", price: 69.99 },
  "Niger": { currency: "USD", price: 69.99 },
  "Nigeria": { currency: "NGN", price: 99900.0 },
  "North Macedonia": { currency: "USD", price: 69.99 },
  "Norway": { currency: "NOK", price: 899.0 },
  "Oman": { currency: "USD", price: 69.99 },
  "Pakistan": { currency: "PKR", price: 19900.0 },
  "Palau": { currency: "USD", price: 69.99 },
  "Panama": { currency: "USD", price: 69.99 },
  "Papua New Guinea": { currency: "USD", price: 69.99 },
  "Paraguay": { currency: "USD", price: 69.99 },
  "Peru": { currency: "PEN", price: 299.9 },
  "Philippines": { currency: "PHP", price: 4490.0 },
  "Poland": { currency: "PLN", price: 299.99 },
  "Portugal": { currency: "EUR", price: 79.99 },
  "Qatar": { currency: "QAR", price: 249.99 },
  "Romania": { currency: "RON", price: 399.99 },
  "Russia": { currency: "RUB", price: 5990.0 },
  "Rwanda": { currency: "USD", price: 69.99 },
  "São Tomé and Príncipe": { currency: "USD", price: 69.99 },
  "Saudi Arabia": { currency: "SAR", price: 299.99 },
  "Senegal": { currency: "USD", price: 79.99 },
  "Serbia": { currency: "EUR", price: 79.99 },
  "Seychelles": { currency: "USD", price: 69.99 },
  "Sierra Leone": { currency: "USD", price: 69.99 },
  "Singapore": { currency: "SGD", price: 99.98 },
  "Slovakia": { currency: "EUR", price: 79.99 },
  "Slovenia": { currency: "EUR", price: 79.99 },
  "Solomon Islands": { currency: "USD", price: 69.99 },
  "South Africa": { currency: "ZAR", price: 1499.99 },
  "Spain": { currency: "EUR", price: 79.99 },
  "Sri Lanka": { currency: "USD", price: 69.99 },
  "St. Kitts and Nevis": { currency: "USD", price: 69.99 },
  "St. Lucia": { currency: "USD", price: 69.99 },
  "St. Vincent and the Grenadines": { currency: "USD", price: 69.99 },
  "Suriname": { currency: "USD", price: 79.99 },
  "Sweden": { currency: "SEK", price: 999.0 },
  "Switzerland": { currency: "CHF", price: 60.0 },
  "Taiwan": { currency: "TWD", price: 2290 },
  "Tajikistan": { currency: "USD", price: 79.99 },
  "Tanzania": { currency: "TZS", price: 199900.0 },
  "Thailand": { currency: "THB", price: 2490.0 },
  "Tonga": { currency: "USD", price: 69.99 },
  "Trinidad and Tobago": { currency: "USD", price: 69.99 },
  "Tunisia": { currency: "USD", price: 69.99 },
  "Türkiye": { currency: "TRY", price: 3999.99 },
  "Turkmenistan": { currency: "USD", price: 69.99 },
  "Turks and Caicos Islands": { currency: "USD", price: 69.99 },
  "Uganda": { currency: "USD", price: 79.99 },
  "Ukraine": { currency: "USD", price: 79.99 },
  "United Arab Emirates": { currency: "AED", price: 249.99 },
  "United Kingdom": { currency: "GBP", price: 69.99 },
  "United States": { currency: "USD", price: 69.99 },
  "Uruguay": { currency: "USD", price: 69.99 },
  "Uzbekistan": { currency: "USD", price: 79.99 },
  "Vanuatu": { currency: "USD", price: 69.99 },
  "Venezuela": { currency: "USD", price: 69.99 },
  "Vietnam": { currency: "VND", price: 1999000 },
  "Yemen": { currency: "USD", price: 69.99 },
  "Zambia": { currency: "USD", price: 79.99 },
  "Zimbabwe": { currency: "USD", price: 79.99 },
};

// Comprehensive timezone to country mapping
export const TIMEZONE_TO_COUNTRY: Record<string, string> = {
  // United States
  "America/New_York": "United States",
  "America/Chicago": "United States",
  "America/Denver": "United States",
  "America/Los_Angeles": "United States",
  "America/Anchorage": "United States",
  "America/Phoenix": "United States",
  "America/Detroit": "United States",
  "America/Indianapolis": "United States",
  "Pacific/Honolulu": "United States",

  // Canada
  "America/Toronto": "Canada",
  "America/Vancouver": "Canada",
  "America/Edmonton": "Canada",
  "America/Winnipeg": "Canada",
  "America/Halifax": "Canada",
  "America/St_Johns": "Canada",

  // United Kingdom
  "Europe/London": "United Kingdom",

  // Europe
  "Europe/Paris": "France",
  "Europe/Berlin": "Germany",
  "Europe/Rome": "Italy",
  "Europe/Madrid": "Spain",
  "Europe/Amsterdam": "Netherlands",
  "Europe/Brussels": "Belgium",
  "Europe/Vienna": "Austria",
  "Europe/Zurich": "Switzerland",
  "Europe/Stockholm": "Sweden",
  "Europe/Oslo": "Norway",
  "Europe/Copenhagen": "Denmark",
  "Europe/Helsinki": "Finland",
  "Europe/Dublin": "Ireland",
  "Europe/Lisbon": "Portugal",
  "Europe/Athens": "Greece",
  "Europe/Warsaw": "Poland",
  "Europe/Prague": "Czech Republic",
  "Europe/Budapest": "Hungary",
  "Europe/Bucharest": "Romania",
  "Europe/Sofia": "Bulgaria",
  "Europe/Zagreb": "Croatia",
  "Europe/Belgrade": "Serbia",
  "Europe/Tallinn": "Estonia",
  "Europe/Riga": "Latvia",
  "Europe/Vilnius": "Lithuania",
  "Europe/Luxembourg": "Luxembourg",
  "Europe/Malta": "Malta",
  "Europe/Bratislava": "Slovakia",
  "Europe/Ljubljana": "Slovenia",
  "Europe/Reykjavik": "Iceland",

  // Asia
  "Asia/Tokyo": "Japan",
  "Asia/Shanghai": "China",
  "Asia/Hong_Kong": "Hong Kong",
  "Asia/Singapore": "Singapore",
  "Asia/Seoul": "Korea, Republic of",
  "Asia/Taipei": "Taiwan",
  "Asia/Bangkok": "Thailand",
  "Asia/Manila": "Philippines",
  "Asia/Jakarta": "Indonesia",
  "Asia/Kuala_Lumpur": "Malaysia",
  "Asia/Ho_Chi_Minh": "Vietnam",
  "Asia/Kolkata": "India",
  "Asia/Dubai": "United Arab Emirates",
  "Asia/Riyadh": "Saudi Arabia",
  "Asia/Qatar": "Qatar",
  "Asia/Kuwait": "Kuwait",
  "Asia/Bahrain": "Bahrain",
  "Asia/Tel_Aviv": "Israel",
  "Asia/Istanbul": "Türkiye",
  "Asia/Karachi": "Pakistan",
  "Asia/Dhaka": "Bangladesh",
  "Asia/Kathmandu": "Nepal",
  "Asia/Colombo": "Sri Lanka",
  "Asia/Yangon": "Myanmar",
  "Asia/Phnom_Penh": "Cambodia",
  "Asia/Vientiane": "Laos",
  "Asia/Tbilisi": "Georgia",
  "Asia/Yerevan": "Armenia",
  "Asia/Baku": "Azerbaijan",
  "Asia/Almaty": "Kazakhstan",
  "Asia/Tashkent": "Uzbekistan",
  "Asia/Bishkek": "Kyrgyzstan",
  "Asia/Dushanbe": "Tajikistan",
  "Asia/Ashgabat": "Turkmenistan",
  "Asia/Kabul": "Afghanistan",
  "Asia/Baghdad": "Iraq",
  "Asia/Amman": "Jordan",
  "Asia/Beirut": "Lebanon",
  "Asia/Damascus": "Syria",
  "Asia/Muscat": "Oman",

  // Australia & Oceania
  "Australia/Sydney": "Australia",
  "Australia/Melbourne": "Australia",
  "Australia/Brisbane": "Australia",
  "Australia/Perth": "Australia",
  "Australia/Adelaide": "Australia",
  "Pacific/Auckland": "New Zealand",
  "Pacific/Fiji": "Fiji",
  "Pacific/Honolulu": "United States",
  "Pacific/Guam": "Guam",
  "Pacific/Port_Moresby": "Papua New Guinea",

  // Africa
  "Africa/Cairo": "Egypt",
  "Africa/Johannesburg": "South Africa",
  "Africa/Lagos": "Nigeria",
  "Africa/Nairobi": "Kenya",
  "Africa/Casablanca": "Morocco",
  "Africa/Algiers": "Algeria",
  "Africa/Tunis": "Tunisia",
  "Africa/Tripoli": "Libya",
  "Africa/Accra": "Ghana",
  "Africa/Addis_Ababa": "Ethiopia",
  "Africa/Dar_es_Salaam": "Tanzania",
  "Africa/Kampala": "Uganda",
  "Africa/Khartoum": "Sudan",
  "Africa/Kinshasa": "Congo, Democratic Republic of the",
  "Africa/Luanda": "Angola",
  "Africa/Maputo": "Mozambique",

  // South America
  "America/Sao_Paulo": "Brazil",
  "America/Buenos_Aires": "Argentina",
  "America/Santiago": "Chile",
  "America/Lima": "Peru",
  "America/Bogota": "Colombia",
  "America/Caracas": "Venezuela",
  "America/Montevideo": "Uruguay",
  "America/Asuncion": "Paraguay",
  "America/La_Paz": "Bolivia",
  "America/Guayaquil": "Ecuador",

  // Central America & Caribbean
  "America/Mexico_City": "Mexico",
  "America/Guatemala": "Guatemala",
  "America/San_Jose": "Costa Rica",
  "America/Panama": "Panama",
  "America/Havana": "Cuba",
  "America/Santo_Domingo": "Dominican Republic",
  "America/Jamaica": "Jamaica",
  "America/Port_of_Spain": "Trinidad and Tobago",
  "America/Barbados": "Barbados",
  "America/Managua": "Nicaragua",
  "America/Tegucigalpa": "Honduras",
  "America/San_Salvador": "El Salvador",
  "America/Belize": "Belize",
};

// Default fallback pricing
export const DEFAULT_PRICING: CountryPrice = {
  currency: "USD",
  price: 1.99,
};

// Currency code to symbol mapping
export const CURRENCY_SYMBOLS: Record<string, string> = {
  USD: "$",
  AUD: "A$",
  EUR: "€",
  GBP: "£",
  BRL: "R$",
  CAD: "C$",
  CLP: "$",
  CNY: "¥",
  COP: "$",
  CZK: "Kč",
  DKK: "kr",
  EGP: "E£",
  HKD: "HK$",
  HUF: "Ft",
  INR: "₹",
  IDR: "Rp",
  ILS: "₪",
  JPY: "¥",
  KZT: "₸",
  KRW: "₩",
  MYR: "RM",
  MXN: "$",
  NOK: "kr",
  NZD: "NZ$",
  NGN: "₦",
  PKR: "₨",
  PEN: "S/",
  PHP: "₱",
  PLN: "zł",
  QAR: "﷼",
  RON: "lei",
  RUB: "₽",
  SAR: "﷼",
  SGD: "S$",
  ZAR: "R",
  SEK: "kr",
  CHF: "CHF",
  TWD: "NT$",
  TZS: "TSh",
  THB: "฿",
  TRY: "₺",
  AED: "د.إ",
  VND: "₫",
};

// Helper function to get currency symbol
export function getCurrencySymbol(currencyCode: string): string {
  return CURRENCY_SYMBOLS[currencyCode] || currencyCode;
}
